### ISSUE TITLE
Add Polling Mode

### ISSUE THREAD

**Issue by ghost** [StarChart-Labs/lure#3]
A new Lure command `lure poll` could be work with a website like postb.in which has a useful API to create an automatic webhooks mode.

Check out [PostBin API docs](https://postb.in/api/) and find the API called `GET /api/bin/<binId>/req/shift`. Essentially it removes the first request element from the bin and returns it, with a body like so: 

```json
{
    "method": "GET",
    "path": "/K45mZSbS",
    "headers": {
        "host": "postb-in.herokuapp.com",
        "connection": "close",
        "user-agent": "curl/7.54.0",
        "accept": "*/*",
        "fly-request-id": "bNpTBfn0k9FeWe2hq9F1PqduAD",
        "fly-app": "postbin-proxy",
        "connect-time": "0",
        "total-route-time": "0"
    },
    "query": {},
    "body": {},
    "ip": "149.117.64.28",
    "binId": "K45mZSbS",
    "inserted": 1556300907604,
    "reqId": "0U3lcEVh"
}
```

In theory a Lure user could run `lure poll --postbin-id=K45mZSbS` and then Lure could hit this endpoint every 10 seconds or so. We could treat the `body` field of the response like the file content from push mode, and grab the X-GitHub-Event header ourselves to use as the event-name.

If we want Lure to not be Github specific we could allow sending another parameter, `--event-header-name` where the user could specify to look in the header called `X-GitHub-Event` (or something else) perhaps?

**Comment by romeara** [comment]
So I think the design I am going to start out with is thus:
`postbin-poll --source-url (postbin-url) --target-url (webhook url) [--poll-frequency (secs)]`

**Comment by romeara** [comment]
Also, possible enhancement for later - if source-url is omitted, use PostBin's APIs to create a Bin. Also, only run for 30 minutes or until the bin returns a 404 or similar indicating it has expired
